name: ShareIt API Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Build Docker images
        run: docker-compose build
  api-tests:
    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci